# Generated by Django 4.0.4 on 2023-06-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_author_product_publishing'),
        ('store', '0004_product_rating_alter_product_description'),
    ]

    operations = [
    ]
