# Generated by Django 4.0.4 on 2022-05-06 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
