# Generated by Django 4.0.4 on 2023-06-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options'),
        ('category', '0006_alter_category_options'),
    ]

    operations = [
    ]
